name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run Jest test
      run: npm test

  sonarqube-analysis:
    name: Análisis de Calidad de Código
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clonación del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ejecución de Escáner SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=mi-proyecto-gestion-sw
            -Dsonar.qualitygate.wait=true
